### ISSUE TITLE
extend appropriate strategies to be able to compute their own areas and other properties

### ISSUE THREAD

**Issue by gvoysey** [lycantropos/hypothesis_geometry#33]
This might exist but I don't see it in the documentation. 

It would be amazing if strategies that generate closed results were able to compute their own perimeters and areas.   I'm writing a great deal of bounding box handling code at the moment, and i'd love more rigorous testing of how we handle that.

**Comment by lycantropos** [comment]
can you please provide an example of the scenario?

**Comment by gvoysey** [comment]
given something like this:
```
from hypothesis_geometry import planar
from hypothesis import strategies

min_coordinate, max_coordinate = -1., 1.
coordinates_type = float
coordinates = strategies.floats(min_coordinate, max_coordinate,
                                 allow_infinity=False,
                                 allow_nan=False)
bounding_boxes = planar.bounding_boxes(coordinates)
bounding_box = bounding_boxes.example()
```

let's say that here we get:
```
bounding_box == (0,1,0,1)  # xmin xmax ymin ymax
```

I'd like to be able to do something like 
```
assert math.isclose(bounding_box.area, 1.0)
assert math.isclose(bounding_box.perimeter, 4.0)
```

obviously that's not quite what it'd look like because `bounding_box` is  a `tuple`;  i'm agnostic on how i'd access `area` and `perimeter` -- maybe utility functions in the package?

**Comment by lycantropos** [comment]
It can be done, but only as a separate package, because the main and only goal of this is to generate pseudo-random data in a simplest way possible and since we are not using area/perimeter anywhere during data creation process I don't think we should include it in this package.

**Comment by lycantropos** [comment]
also for your particular case with bounding boxes I think you can write those 2 yourself, it shouldn't be hard for axis-aligned rectangles
