### ISSUE TITLE
Strategy for linestrings

### ISSUE THREAD

**Issue by LostFan123** [lycantropos/hypothesis_geometry#9]
I'm proposing to add a strategy for linestrings, since it's quite a common geometry object used in GIS and other geometry-related applications. See, for example, [`LineString` in SQL docs](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/linestring?view=sql-server-ver15) and [`LineString` in Shapely docs](https://shapely.readthedocs.io/en/latest/manual.html#linestrings).

Also see the [wikipedia entry](https://en.wikipedia.org/wiki/Polygonal_chain) on linestrings.

**Comment by lycantropos** [comment]
How should it be called? `polylines` seems less GIS-centric to me.

What output should be? A `list` of `Point`s?

Which parameters should it accept? Should we create all sorts of them or add an ability to build non-intersecting ones?

We can start from straightforward implementation and add options/another strategies further I guess.

**Comment by LostFan123** [comment]
The `polylines` sounds good. Alternatively, it could be `chains`, as in "polygonal chain". But it's difficult to see which one is used more in the context of geometry since the word "chain" is ambiguous. I'd personally go with `polylines`. It's just how would we call a strategy to generate [`MultiLineString`s-like objects](https://shapely.readthedocs.io/en/latest/manual.html#MultiLineString)? `multipolylines`?

The output as a `list` of `Point`s seems obvious to me. Are there any alternatives?

About the input parameters. We could start with something like this to generate open complex polylines (all points unique, self-intersections are possible):
```
def polylines(points: Strategy[Point],
              *,
              min_size: int = 0,
              max_size: Optional[int] = None
              ) -> Strategy[Polyline]:
```
I'm just unsure about the min number of points. Shapely, for example, produces an empty `LineString` if it gets no points, and throws an error if it gets only one point.

Later on, we could add parameters to generate also simple polylines (without self-intersections), closed polylines, and maybe even monotone polylines as in [wikipedia article](https://en.wikipedia.org/wiki/Polygonal_chain). I see also in [SQL docs](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/linestring?view=sql-server-ver15) that they define valid/invalid linestrings, while in Shapely all linestrings are valid. Not sure now if it is needed, but we *could* consider optionally filtering out polylines with segments lying on each other.

Another question is how is it related to the currently existing `contours` strategy?

**Comment by lycantropos** [comment]
`contours` in this context looks like simple polylines (that can be closed by repeating first vertex in the end)

I don't like `min_size` being less than `2` because absence of points should not be considered as a line, neither should a single point, so we can start with default `min_size=2` and raise an error if it less.

About `multipolylines` -- we'll see, for now I'm not planning to support such objects until there is no request from users.
